-- MySQL Script generated by MySQL Workbench
-- Sun 25 Dec 2022 22:10:20 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfolio_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `portfolio_db` ;

-- -----------------------------------------------------
-- Schema portfolio_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio_db` ;
USE `portfolio_db` ;

-- -----------------------------------------------------
-- Table `portfolio_db`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_db`.`Persona` (
  `id` INT NOT NULL,
  `username` VARCHAR(8) NULL,
  `password` VARCHAR(12) NULL COMMENT '	',
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `profesion` VARCHAR(45) NULL,
  `email` VARCHAR(45) COLLATE 'Default Collation' NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `sobre_mi` VARCHAR(650) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio_db`.`Experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_db`.`Experiencia` (
  `id` INT NOT NULL,
  `nombre_empresa` VARCHAR(60) NULL,
  `cargo` VARCHAR(45) NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `fecha_fin` VARCHAR(45) NULL,
  `ubicacion` VARCHAR(45) NULL,
  `descripcion` VARCHAR(300) NULL,
  `Persona_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Experiencia_Persona_idx` (`Persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_Experiencia_Persona`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `portfolio_db`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio_db`.`Educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_db`.`Educacion` (
  `id` INT NOT NULL,
  `nombre_instituto` VARCHAR(60) NULL,
  `Titulo` VARCHAR(45) NULL,
  `fecha_inicio` YEAR(4) NULL,
  `fecha_fin` YEAR(4) NULL,
  `descripcion` VARCHAR(200) NULL,
  `Persona_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Educacion_Persona1_idx` (`Persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_Educacion_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `portfolio_db`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio_db`.`Skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_db`.`Skill` (
  `id` INT NOT NULL,
  `nombre_skill` VARCHAR(12) NULL,
  `Persona_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Skill_Persona1_idx` (`Persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_Skill_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `portfolio_db`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio_db`.`Idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_db`.`Idioma` (
  `id` INT NOT NULL,
  `nombre_idioma` VARCHAR(12) NULL,
  `Persona_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Idioma_Persona1_idx` (`Persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_Idioma_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `portfolio_db`.`Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
